spring:
  application:
    name: pettingCore
  datasource:
    url: "@datasource.url@"
    username: "@datasource.username@"
    password: "@datasource.password@"
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: "@jpa.properties.hibernate.dialect@"
    show-sql: true
  jackson:
    time-zone: GMT-3
    serialization:
      fail-on-empty-beans: false
      write-null-map-values: false
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoint:
    auditevents:
      enabled: false
  endpoints:
    web:
      cors:
        allowed-origins: *
info:
  version: "@project.version@"
    properties.from: "@properties.from@"
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"